spring:
  application:
    name: Library-APIRest
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library-db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080
